site_name: Todo App Documentation
site_url: https://anithanarayanswamy.github.io/My-Documentation/

nav:
  - Home: index.md
  - TodoApp: todo-app.md
  - Test: test.md
    
plugins:
- search
- mkdocstrings