site_name: Todo App Documentation
repo_url: https://anithanarayanswamy.github.io/My-Documentation/

nav:
  - Home: index.md
  - APP: todo-app.md
  - TEST: test.md
    
plugins:
- search
- mkdocstrings